### ISSUE TITLE
.grd output bytes size much smaller than expected (as in the code)

### ISSUE THREAD

**Issue by merlinyx** [jsnln/fite#3]
Hi! I was trying to run step1 of the pipeline with a `<subject>_minimal_tpose.ply` file and I ran into the error "ValueError: bytes length not a multiple of item size" around these [lines](https://github.com/jsnln/fite/blob/main/step1_diffused_skinning/compute_diffused_skinning.py#L135-L138). It was caused by the fact that the generated .grd files have only 524391~524393 bytes, which is much smaller than `grid_res ** 3 * 8` when `skinning_grid_depth` is 8, and is also not a power of 2. Hacking the `grid_res` is probably not a good idea; may I know what might be causing this and how I should solve this? Thank you!

**Comment by jsnln** [comment]
Hi, the `.grd` files are the output of the `PointInterpolant` app. If it was run correctly, each `.grd` file should be 128MB. You can check whether `PointInterpolant` terminates correctly. You can also check the temporary input files to `PointInterpolant` in `data_tmp_constraints`. Each `cano_data_lbs_val_xx.xyz` contain a 6890x(3+1) matrix, consisting of SMPL vertex coordinates and the skinning weights. Each `cano_data_lbs_grad_xx.xyz` contain a 6890x(3+3) matrix, consisting of vertex coordinates and the skinning gradients as described in the paper.

**Comment by merlinyx** [comment]
I see, thank you for the tips! I'll take a look!
